package com.yjz.cross.monitor.model;

public class AccessLogData {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column access_log_data.id
     * @mbggenerated  Mon Jul 03 13:49:55 CST 2017
     */
    private Integer id;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column access_log_data.request_id
     * @mbggenerated  Mon Jul 03 13:49:55 CST 2017
     */
    private String requestId;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column access_log_data.server_address
     * @mbggenerated  Mon Jul 03 13:49:55 CST 2017
     */
    private String serverAddress;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column access_log_data.client_address
     * @mbggenerated  Mon Jul 03 13:49:55 CST 2017
     */
    private String clientAddress;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column access_log_data.req_json
     * @mbggenerated  Mon Jul 03 13:49:55 CST 2017
     */
    private String reqJson;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column access_log_data.resp_json
     * @mbggenerated  Mon Jul 03 13:49:55 CST 2017
     */
    private String respJson;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column access_log_data.cost_time_mills
     * @mbggenerated  Mon Jul 03 13:49:55 CST 2017
     */
    private Integer costTimeMills;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column access_log_data.id
     * @return  the value of access_log_data.id
     * @mbggenerated  Mon Jul 03 13:49:55 CST 2017
     */
    public Integer getId()
    {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column access_log_data.id
     * @param id  the value for access_log_data.id
     * @mbggenerated  Mon Jul 03 13:49:55 CST 2017
     */
    public void setId(Integer id)
    {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column access_log_data.request_id
     * @return  the value of access_log_data.request_id
     * @mbggenerated  Mon Jul 03 13:49:55 CST 2017
     */
    public String getRequestId()
    {
        return requestId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column access_log_data.request_id
     * @param requestId  the value for access_log_data.request_id
     * @mbggenerated  Mon Jul 03 13:49:55 CST 2017
     */
    public void setRequestId(String requestId)
    {
        this.requestId = requestId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column access_log_data.server_address
     * @return  the value of access_log_data.server_address
     * @mbggenerated  Mon Jul 03 13:49:55 CST 2017
     */
    public String getServerAddress()
    {
        return serverAddress;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column access_log_data.server_address
     * @param serverAddress  the value for access_log_data.server_address
     * @mbggenerated  Mon Jul 03 13:49:55 CST 2017
     */
    public void setServerAddress(String serverAddress)
    {
        this.serverAddress = serverAddress;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column access_log_data.client_address
     * @return  the value of access_log_data.client_address
     * @mbggenerated  Mon Jul 03 13:49:55 CST 2017
     */
    public String getClientAddress()
    {
        return clientAddress;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column access_log_data.client_address
     * @param clientAddress  the value for access_log_data.client_address
     * @mbggenerated  Mon Jul 03 13:49:55 CST 2017
     */
    public void setClientAddress(String clientAddress)
    {
        this.clientAddress = clientAddress;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column access_log_data.req_json
     * @return  the value of access_log_data.req_json
     * @mbggenerated  Mon Jul 03 13:49:55 CST 2017
     */
    public String getReqJson()
    {
        return reqJson;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column access_log_data.req_json
     * @param reqJson  the value for access_log_data.req_json
     * @mbggenerated  Mon Jul 03 13:49:55 CST 2017
     */
    public void setReqJson(String reqJson)
    {
        this.reqJson = reqJson;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column access_log_data.resp_json
     * @return  the value of access_log_data.resp_json
     * @mbggenerated  Mon Jul 03 13:49:55 CST 2017
     */
    public String getRespJson()
    {
        return respJson;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column access_log_data.resp_json
     * @param respJson  the value for access_log_data.resp_json
     * @mbggenerated  Mon Jul 03 13:49:55 CST 2017
     */
    public void setRespJson(String respJson)
    {
        this.respJson = respJson;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column access_log_data.cost_time_mills
     * @return  the value of access_log_data.cost_time_mills
     * @mbggenerated  Mon Jul 03 13:49:55 CST 2017
     */
    public Integer getCostTimeMills()
    {
        return costTimeMills;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column access_log_data.cost_time_mills
     * @param costTimeMills  the value for access_log_data.cost_time_mills
     * @mbggenerated  Mon Jul 03 13:49:55 CST 2017
     */
    public void setCostTimeMills(Integer costTimeMills)
    {
        this.costTimeMills = costTimeMills;
    }
}