package com.yjz.cross.monitor.dao;

import com.yjz.cross.monitor.model.AccessLog;

public interface AccessLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table access_log
     *
     * @mbggenerated Fri Jun 30 15:15:16 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table access_log
     *
     * @mbggenerated Fri Jun 30 15:15:16 CST 2017
     */
    int insert(AccessLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table access_log
     *
     * @mbggenerated Fri Jun 30 15:15:16 CST 2017
     */
    int insertSelective(AccessLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table access_log
     *
     * @mbggenerated Fri Jun 30 15:15:16 CST 2017
     */
    AccessLog selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table access_log
     *
     * @mbggenerated Fri Jun 30 15:15:16 CST 2017
     */
    int updateByPrimaryKeySelective(AccessLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table access_log
     *
     * @mbggenerated Fri Jun 30 15:15:16 CST 2017
     */
    int updateByPrimaryKey(AccessLog record);
}